
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.UIManager UIManager;

	private global::Gtk.Action ArquivoAction;

	private global::Gtk.Action SairAction;

	private global::Gtk.VBox vbox2;

	private global::Gtk.HBox hbox2;

	private global::Gtk.MenuBar menubar1;

	private global::Gtk.HBox hbox3;

	private global::Gtk.VBox vbox7;

	private global::Gtk.Label label1;

	private global::Gtk.ComboBox cmbJogo;

	private global::Gtk.VBox vbox8;

	private global::Gtk.Label label2;

	private global::Gtk.HBox hbox1;

	private global::Gtk.ComboBox cmbJogoAposta;

	private global::Gtk.Label label4;

	private global::Gtk.VBox vbox9;

	private global::Gtk.Label label3;

	private global::Gtk.HBox hbox4;

	private global::Gtk.ComboBox cmbJogoQuantidade;

	private global::Gtk.Label label5;

	private global::Gtk.VBox vbox1;

	private global::Gtk.Button btnGerar;

	private global::Gtk.ScrolledWindow GtkScrolledWindow;

	private global::Gtk.TreeView tvResultado;

	private global::Gtk.HBox hboxSalvar;

	private global::Gtk.Button btnSalvar;

	protected virtual void Build()
	{
		global::Stetic.Gui.Initialize(this);
		// Widget MainWindow
		this.UIManager = new global::Gtk.UIManager();
		global::Gtk.ActionGroup w1 = new global::Gtk.ActionGroup("Default");
		this.ArquivoAction = new global::Gtk.Action("ArquivoAction", global::Mono.Unix.Catalog.GetString("A_rquivo"), null, null);
		this.ArquivoAction.ShortLabel = global::Mono.Unix.Catalog.GetString("A_rquivo");
		w1.Add(this.ArquivoAction, null);
		this.SairAction = new global::Gtk.Action("SairAction", global::Mono.Unix.Catalog.GetString("Sai_r"), null, null);
		this.SairAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Sai_r");
		w1.Add(this.SairAction, null);
		this.UIManager.InsertActionGroup(w1, 0);
		this.AddAccelGroup(this.UIManager.AccelGroup);
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString("Analisador e gerador lotérico ltk");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.vbox2 = new global::Gtk.VBox();
		this.vbox2.Name = "vbox2";
		this.vbox2.Spacing = 6;
		// Container child vbox2.Gtk.Box+BoxChild
		this.hbox2 = new global::Gtk.HBox();
		this.hbox2.Name = "hbox2";
		this.hbox2.Spacing = 6;
		// Container child hbox2.Gtk.Box+BoxChild
		this.UIManager.AddUiFromString("<ui><menubar name='menubar1'><menu name='ArquivoAction' action='ArquivoAction'><menuitem name='SairAction' action='SairAction'/></menu></menubar></ui>");
		this.menubar1 = ((global::Gtk.MenuBar)(this.UIManager.GetWidget("/menubar1")));
		this.menubar1.Name = "menubar1";
		this.hbox2.Add(this.menubar1);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.menubar1]));
		w2.Position = 0;
		w2.Expand = false;
		w2.Fill = false;
		this.vbox2.Add(this.hbox2);
		global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.hbox2]));
		w3.Position = 0;
		w3.Expand = false;
		w3.Fill = false;
		// Container child vbox2.Gtk.Box+BoxChild
		this.hbox3 = new global::Gtk.HBox();
		this.hbox3.Name = "hbox3";
		this.hbox3.Spacing = 6;
		// Container child hbox3.Gtk.Box+BoxChild
		this.vbox7 = new global::Gtk.VBox();
		this.vbox7.Name = "vbox7";
		this.vbox7.Spacing = 2;
		this.vbox7.BorderWidth = ((uint)(9));
		// Container child vbox7.Gtk.Box+BoxChild
		this.label1 = new global::Gtk.Label();
		this.label1.Name = "label1";
		this.label1.LabelProp = global::Mono.Unix.Catalog.GetString("Jogo");
		this.vbox7.Add(this.label1);
		global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox7[this.label1]));
		w4.Position = 0;
		w4.Expand = false;
		w4.Fill = false;
		// Container child vbox7.Gtk.Box+BoxChild
		this.cmbJogo = global::Gtk.ComboBox.NewText();
		this.cmbJogo.Name = "cmbJogo";
		this.vbox7.Add(this.cmbJogo);
		global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vbox7[this.cmbJogo]));
		w5.Position = 1;
		this.hbox3.Add(this.vbox7);
		global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.vbox7]));
		w6.Position = 0;
		w6.Expand = false;
		w6.Fill = false;
		// Container child hbox3.Gtk.Box+BoxChild
		this.vbox8 = new global::Gtk.VBox();
		this.vbox8.Name = "vbox8";
		this.vbox8.Spacing = 2;
		this.vbox8.BorderWidth = ((uint)(9));
		// Container child vbox8.Gtk.Box+BoxChild
		this.label2 = new global::Gtk.Label();
		this.label2.Name = "label2";
		this.label2.Xalign = 0F;
		this.label2.LabelProp = global::Mono.Unix.Catalog.GetString("Jogar apostas com:");
		this.vbox8.Add(this.label2);
		global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.vbox8[this.label2]));
		w7.Position = 0;
		w7.Expand = false;
		w7.Fill = false;
		// Container child vbox8.Gtk.Box+BoxChild
		this.hbox1 = new global::Gtk.HBox();
		this.hbox1.Name = "hbox1";
		this.hbox1.Spacing = 6;
		// Container child hbox1.Gtk.Box+BoxChild
		this.cmbJogoAposta = global::Gtk.ComboBox.NewText();
		this.cmbJogoAposta.Name = "cmbJogoAposta";
		this.hbox1.Add(this.cmbJogoAposta);
		global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.cmbJogoAposta]));
		w8.Position = 0;
		w8.Expand = false;
		// Container child hbox1.Gtk.Box+BoxChild
		this.label4 = new global::Gtk.Label();
		this.label4.Name = "label4";
		this.label4.Xalign = 0F;
		this.label4.LabelProp = global::Mono.Unix.Catalog.GetString("números");
		this.hbox1.Add(this.label4);
		global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.label4]));
		w9.Position = 1;
		w9.Expand = false;
		this.vbox8.Add(this.hbox1);
		global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.vbox8[this.hbox1]));
		w10.Position = 1;
		w10.Expand = false;
		w10.Fill = false;
		this.hbox3.Add(this.vbox8);
		global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.vbox8]));
		w11.Position = 1;
		w11.Expand = false;
		w11.Fill = false;
		// Container child hbox3.Gtk.Box+BoxChild
		this.vbox9 = new global::Gtk.VBox();
		this.vbox9.Name = "vbox9";
		this.vbox9.Spacing = 2;
		this.vbox9.BorderWidth = ((uint)(9));
		// Container child vbox9.Gtk.Box+BoxChild
		this.label3 = new global::Gtk.Label();
		this.label3.Name = "label3";
		this.label3.Xalign = 0F;
		this.label3.LabelProp = global::Mono.Unix.Catalog.GetString("Quantidade de apostas:");
		this.vbox9.Add(this.label3);
		global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.vbox9[this.label3]));
		w12.Position = 0;
		w12.Expand = false;
		w12.Fill = false;
		// Container child vbox9.Gtk.Box+BoxChild
		this.hbox4 = new global::Gtk.HBox();
		this.hbox4.Name = "hbox4";
		this.hbox4.Spacing = 6;
		// Container child hbox4.Gtk.Box+BoxChild
		this.cmbJogoQuantidade = global::Gtk.ComboBox.NewText();
		this.cmbJogoQuantidade.Name = "cmbJogoQuantidade";
		this.hbox4.Add(this.cmbJogoQuantidade);
		global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.hbox4[this.cmbJogoQuantidade]));
		w13.Position = 0;
		// Container child hbox4.Gtk.Box+BoxChild
		this.label5 = new global::Gtk.Label();
		this.label5.Name = "label5";
		this.label5.Xalign = 0F;
		this.label5.LabelProp = global::Mono.Unix.Catalog.GetString("números");
		this.hbox4.Add(this.label5);
		global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.hbox4[this.label5]));
		w14.Position = 1;
		this.vbox9.Add(this.hbox4);
		global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.vbox9[this.hbox4]));
		w15.Position = 1;
		w15.Expand = false;
		w15.Fill = false;
		this.hbox3.Add(this.vbox9);
		global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.vbox9]));
		w16.Position = 2;
		w16.Expand = false;
		w16.Fill = false;
		// Container child hbox3.Gtk.Box+BoxChild
		this.vbox1 = new global::Gtk.VBox();
		this.vbox1.Name = "vbox1";
		this.vbox1.BorderWidth = ((uint)(9));
		// Container child vbox1.Gtk.Box+BoxChild
		this.btnGerar = new global::Gtk.Button();
		this.btnGerar.CanFocus = true;
		this.btnGerar.Name = "btnGerar";
		this.btnGerar.UseUnderline = true;
		this.btnGerar.Label = global::Mono.Unix.Catalog.GetString("Gerar jogos aleatórios");
		this.vbox1.Add(this.btnGerar);
		global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.btnGerar]));
		w17.PackType = ((global::Gtk.PackType)(1));
		w17.Position = 1;
		w17.Expand = false;
		w17.Fill = false;
		this.hbox3.Add(this.vbox1);
		global::Gtk.Box.BoxChild w18 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.vbox1]));
		w18.Position = 3;
		w18.Expand = false;
		w18.Fill = false;
		this.vbox2.Add(this.hbox3);
		global::Gtk.Box.BoxChild w19 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.hbox3]));
		w19.Position = 1;
		w19.Expand = false;
		w19.Fill = false;
		// Container child vbox2.Gtk.Box+BoxChild
		this.GtkScrolledWindow = new global::Gtk.ScrolledWindow();
		this.GtkScrolledWindow.Name = "GtkScrolledWindow";
		this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
		this.tvResultado = new global::Gtk.TreeView();
		this.tvResultado.CanFocus = true;
		this.tvResultado.Name = "tvResultado";
		this.GtkScrolledWindow.Add(this.tvResultado);
		this.vbox2.Add(this.GtkScrolledWindow);
		global::Gtk.Box.BoxChild w21 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.GtkScrolledWindow]));
		w21.Position = 2;
		// Container child vbox2.Gtk.Box+BoxChild
		this.hboxSalvar = new global::Gtk.HBox();
		this.hboxSalvar.Name = "hboxSalvar";
		this.hboxSalvar.Spacing = 6;
		// Container child hboxSalvar.Gtk.Box+BoxChild
		this.btnSalvar = new global::Gtk.Button();
		this.btnSalvar.CanFocus = true;
		this.btnSalvar.Name = "btnSalvar";
		this.btnSalvar.UseUnderline = true;
		this.btnSalvar.BorderWidth = ((uint)(6));
		this.btnSalvar.Label = global::Mono.Unix.Catalog.GetString("Salvar em um arquivo...");
		this.hboxSalvar.Add(this.btnSalvar);
		global::Gtk.Box.BoxChild w22 = ((global::Gtk.Box.BoxChild)(this.hboxSalvar[this.btnSalvar]));
		w22.PackType = ((global::Gtk.PackType)(1));
		w22.Position = 2;
		w22.Expand = false;
		w22.Fill = false;
		this.vbox2.Add(this.hboxSalvar);
		global::Gtk.Box.BoxChild w23 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.hboxSalvar]));
		w23.Position = 3;
		w23.Expand = false;
		w23.Fill = false;
		this.Add(this.vbox2);
		if ((this.Child != null))
		{
			this.Child.ShowAll();
		}
		this.DefaultWidth = 815;
		this.DefaultHeight = 418;
		this.Show();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler(this.OnDeleteEvent);
		this.DefaultActivated += new global::System.EventHandler(this.OnDefaultActivated);
		this.cmbJogo.Changed += new global::System.EventHandler(this.OnCmbJogoChanged);
		this.btnGerar.Clicked += new global::System.EventHandler(this.OnBtnGerarClicked);
	}
}
